name: Run linting

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint-typescript:
    name: Run typescript linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint on TypeScript files
        run: npx eslint "**/*.ts" --ignore-pattern "frontend/**"

      - name: Run Prettier on TypeScript files
        run: npx prettier --check "**/*.ts"

  lint-solidity:
    name: Run solidity linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run Solhint on Solidity files
        run: |
          solhint_output=$(npx solhint "contracts/**/*.sol")
          echo "$solhint_output"
          if [ -n "$solhint_output" ]; then
            exit 1
          fi

      - name: Run Prettier on Solidity files
        run: npx prettier --check --plugin=prettier-plugin-solidity 'contracts/**/*.sol'

  lint-react:
    name: Run React linter
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node modules for frontend
        uses: actions/cache@v2
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-frontend-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-node-

      - name: Install frontend dependencies
        run: npm ci

      - name: Run ESLint on React files
        run: npx eslint "src/**/*.{js,jsx,ts,tsx}"

      - name: Run Prettier on React files
        run: npx prettier --check "src/**/*.{js,jsx,ts,tsx}"