name: Run linting

on:
  workflow_dispatch:
  pull_request:

jobs:
  lint-typescript:
    name: Run typescript linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint on TypeScript files
        run: npx eslint "**/*.ts"

      - name: Run Prettier on TypeScript files
        run: npx prettier --check "**/*.ts"

  lint-solidity:
    name: Run solidity linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run Solhint on Solidity files
        run: npx solhint "contracts/**/*.sol"

      - name: Run Prettier on Solidity files
        run: npx prettier --check --plugin=prettier-plugin-solidity 'contracts/**/*.sol'
