name: Run tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Run npm test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: hardhat/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
        working-directory: hardhat

      - name: Run tests
        run: npm test
        working-directory: hardhat
